# .intent/meta.yaml
version: "2.0.0" # A2 Autonomy Achievement - Autonomous Code Generation

charter:
  constitution:
    active_version: "charter/constitution/ACTIVE"
    governance_framework: "charter/constitution/governance_framework.yaml"
    precedence_rules: "charter/constitution/precedence_rules.yaml"
    approvers: "charter/constitution/approvers.yaml"
    critical_paths: "charter/constitution/critical_paths.yaml"
    immutable_principles: "charter/constitution/immutable_principles.yaml"

  policies:
    safety_framework: "charter/policies/safety_framework.yaml"
    agent_governance: "charter/policies/agent_governance.yaml"
    code_standards: "charter/policies/code_standards.yaml"
    dependency_injection_policy: "charter/policies/dependency_injection_policy.yaml"
    data_governance: "charter/policies/data_governance.yaml"
    operations: "charter/policies/operations.yaml"
    quality_assurance: "charter/policies/quality_assurance.yaml"
    decorator_governance: "charter/policies/decorator_governance.yaml"

  patterns:
    agent_patterns: "charter/patterns/agent_patterns.yaml"
    atomic_actions: "charter/patterns/atomic_actions.yaml"
    body_contracts: "charter/patterns/body_contracts.yaml"
    command_patterns: "charter/patterns/command_patterns.yaml"
    irritation_heuristic: "charter/patterns/irritation_heuristic.yaml"
    service_patterns: "charter/patterns/service_patterns.yaml"
    user_interface: "charter/patterns/user_interface.yaml"
    vector_service_standards: "charter/patterns/vector_service_standards.yaml"
    workflow_patterns: "charter/patterns/workflow_patterns.yaml"

  schemas:
    policy_schema: "charter/schemas/policy_schema.json"
    agent:
      agent_policy_schema: "charter/schemas/agent/agent_policy_schema.json"
      cognitive_roles_schema: "charter/schemas/agent/cognitive_roles_schema.json"
      micro_proposal_policy_schema: "charter/schemas/agent/micro_proposal_policy_schema.json"
      resource_manifest_policy_schema: "charter/schemas/agent/resource_manifest_policy_schema.json"
    code:
      capability_tag_schema: "charter/schemas/code/capability_tag_schema.json"
      dependency_injection_policy_schema: "charter/schemas/code/dependency_injection_policy_schema.json"
      knowledge_graph_entry_schema: "charter/schemas/code/knowledge_graph_entry_schema.json"
    constitutional:
      intent_bundle_schema: "charter/schemas/constitutional/intent_bundle_schema.json"
      intent_crate_schema: "charter/schemas/constitutional/intent_crate_schema.json"
      proposal_schema: "charter/schemas/constitutional/proposal_schema.json"
    data:
      database_policy_schema: "charter/schemas/data/database_policy_schema.json"
      database_schema: "charter/schemas/data/database_schema.yaml"
    governance:
      available_actions_policy_schema: "charter/schemas/governance/available_actions_policy_schema.json"
      cli_registry_schema: "charter/schemas/governance/cli_registry_schema.json"
      enforcement_model_schema: "charter/schemas/governance/enforcement_model_schema.json"
      intent_guard_schema: "charter/schemas/governance/intent_guard_schema.json"
      reporting_policy_schema: "charter/schemas/governance/reporting_policy_schema.json"
      risk_classification_policy_schema: "charter/schemas/governance/risk_classification_policy_schema.json"
    operations:
      canary_policy_schema: "charter/schemas/operations/canary_policy_schema.json"
      config_schema: "charter/schemas/operations/config_schema.yaml"
      runtime_requirements_schema: "charter/schemas/operations/runtime_requirements_schema.json"
      workflows_policy_schema: "charter/schemas/operations/workflows_policy_schema.json"

mind:
  project_manifest: "mind/project_manifest.yaml"
  northstar: "mind/northstar.yaml"
  config:
    local_mode: "mind/config/local_mode.yaml"
    runtime_requirements: "mind/config/runtime_requirements.yaml"
  ir:
    incident_log: "mind/ir/incident_log.yaml"
    triage_log: "mind/ir/triage_log.yaml"
  knowledge:
    domain_definitions: "mind/knowledge/domain_definitions.yaml"
    project_structure: "mind/knowledge/project_structure.yaml"
    entry_point_patterns: "mind/knowledge/entry_point_patterns.yaml"
  mind_export:
    cognitive_roles: "mind_export/cognitive_roles.yaml"
    resource_manifest: "mind_export/resource_manifest.yaml"
    capabilities: "mind_export/capabilities.yaml"
    symbols: "mind_export/symbols.yaml"
    links: "mind_export/links.yaml"
    northstar: "mind_export/northstar.yaml"
  prompts:
    capability_consolidator: "mind/prompts/capability_consolidator.prompt"
    capability_definer: "mind/prompts/capability_definer.prompt"
    code_peer_review: "mind/prompts/code_peer_review.prompt"
    constitutional_review: "mind/prompts/constitutional_review.prompt"
    coverage_strategy: "mind/prompts/coverage_strategy.prompt"
    create_file_planner: "mind/prompts/create_file_planner.prompt"
    docs_clarity_review: "mind/prompts/docs_clarity_review.prompt"
    enrich_symbol: "mind/prompts/enrich_symbol.prompt"
    fix_capability_manifest: "mind/prompts/fix_capability_manifest.prompt"
    fix_function_docstring: "mind/prompts/fix_function_docstring.prompt"
    fix_header: "mind/prompts/fix_header.prompt"
    fix_line_length: "mind/prompts/fix_line_length.prompt"
    goal_assessor: "mind/prompts/goal_assessor.prompt"
    intent_translator: "mind/prompts/intent_translator.prompt"
    micro_planner: "mind/prompts/micro_planner.prompt"
    module_docstring_writer: "mind/prompts/module_docstring_writer.prompt"
    new_capability_generator: "mind/prompts/new_capability_generator.prompt"
    planner_agent: "mind/prompts/planner_agent.prompt"
    refactor_for_clarity: "mind/prompts/refactor_for_clarity.prompt"
    refactor_outlier: "mind/prompts/refactor_outlier.prompt"
    standard_task_generator: "mind/prompts/standard_task_generator.prompt"
    test_fixer: "mind/prompts/test_fixer.prompt"
    test_generator: "mind/prompts/test_generator.prompt"
    vectorizer: "mind/prompts/vectorizer.prompt"
  context:
    schema: "context/schema.yaml"
    policy: "context/policy.yaml"
    domains: "knowledge/domains.yaml"
