# .intent/meta.yaml
id: intent_meta_registry
title: CORE Intent Meta Registry
type: meta_registry
status: active
owners:
  accountable: Governance Lead
  responsible:
  - Core Maintainer
review:
  frequency: 12 months
schema_id: meta.registry
version: 2.3.0
updated_at: '2025-12-16T10:30:00.000000+00:00'
charter:
  constitution:
    GLOBAL-DOCUMENT-META-SCHEMA: charter/constitution/GLOBAL-DOCUMENT-META-SCHEMA.yaml
    META-SCHEMA: charter/constitution/META-SCHEMA.yaml
    authority: charter/constitution/authority.yaml
    boundaries: charter/constitution/boundaries.yaml
    risk_classification: charter/constitution/risk_classification.yaml
  schemas:
    data:
      agent_memory_schema: charter/schemas/data/agent_memory_schema.yaml # NEW
      database_schema: charter/schemas/data/database_schema.yaml
    operations:
      config_schema: charter/schemas/operations/config_schema.yaml
      conversational_context_bundle_schema: charter/schemas/operations/conversational_context_bundle_schema.yaml
  standards:
    architecture:
      agent_governance: charter/standards/architecture/agent_governance.yaml
      agent_patterns: charter/standards/architecture/agent_patterns.yaml
      atomic_actions: charter/standards/architecture/atomic_actions.yaml
      body_contracts: charter/standards/architecture/body_contracts.yaml
      command_patterns: charter/standards/architecture/command_patterns.yaml
      decorator_governance: charter/standards/architecture/decorator_governance.yaml
      dependency_injection: charter/standards/architecture/dependency_injection.yaml
      event_schema: charter/standards/architecture/event_schema_standard.yaml # NEW
      irritation_heuristic: charter/standards/architecture/irritation_heuristic.yaml
      layer_contracts: charter/standards/architecture/layer_contracts.yaml
      service_patterns: charter/standards/architecture/service_patterns.yaml
      tool_definitions: charter/standards/architecture/tool_definition_standard.yaml # NEW
      user_interface: charter/standards/architecture/user_interface.yaml
      vector_service_standards: charter/standards/architecture/vector_service_standards.yaml
      workflow_patterns: charter/standards/architecture/workflow_patterns.yaml
    code:
      purity: charter/standards/code/purity.yaml
    code_standards: charter/standards/code_standards.yaml
    data:
      governance: charter/standards/data/governance.yaml
    logging_standards: charter/standards/logging_standards.yaml
    operations:
      code_execution: charter/standards/operations/code_execution.yaml
      observability: charter/standards/operations/observability.yaml
      operations: charter/standards/operations/operations.yaml
      pattern_vectorization: charter/standards/operations/pattern_vectorization.yaml
      quality_assurance: charter/standards/operations/quality_assurance.yaml
      safety: charter/standards/operations/safety.yaml
      secrets_management: charter/standards/operations/secrets_management.yaml # NEW
    policy_integrity: charter/standards/policy_integrity.yaml
mind:
  config:
    local_mode: mind/config/local_mode.yaml
    runtime_requirements: mind/config/runtime_requirements.yaml
  ir:
    triage_log: mind/ir/triage_log.yaml
  knowledge:
    domain_definitions: mind/knowledge/domain_definitions.yaml
    entry_point_patterns: mind/knowledge/entry_point_patterns.yaml
    project_structure: mind/knowledge/project_structure.yaml
  northstar: mind/northstar.yaml
  project_manifest: mind/project_manifest.yaml
context:
  policy: context/policy.yaml
  schema: context/schema.yaml
knowledge:
  domains: knowledge/domains.yaml
