version: "2.0.0" # Version bump for v2.1 Schema Migration
# PURPOSE: This is the master index for the entire CORE constitution. It maps
# abstract concepts to their concrete file paths, fully embracing the new
# hierarchical policy structure for maximum clarity and governance.

charter:
  constitution:
    active_version: "charter/constitution/ACTIVE"
    amendment_process: "charter/constitution/amendment_process.md"
    approvers: "charter/constitution/approvers.yaml"
    critical_paths: "charter/constitution/critical_paths.yaml"
    operator_lifecycle: "charter/constitution/operator_lifecycle.md"

  mission:
    manifesto: "charter/mission/manifesto.md"
    northstar: "charter/mission/northstar.yaml"
    principles: "charter/mission/principles.yaml"

  policies:
    safety_policy: "charter/policies/safety_policy.yaml"

    agent:
      agent_policy: "charter/policies/agent/agent_policy.yaml"
      micro_proposal_policy: "charter/policies/agent/micro_proposal_policy.yaml"

    code:
      capability_linter_policy: "charter/policies/code/capability_linter_policy.yaml"
      code_health_policy: "charter/policies/code/code_health_policy.yaml"
      code_style_policy: "charter/policies/code/code_style_policy.yaml"
      naming_conventions_policy: "charter/policies/code/naming_conventions_policy.yaml"
      refactoring_patterns_policy: "charter/policies/code/refactoring_patterns_policy.yaml"

    data:
      database_policy: "charter/policies/data/database_policy.yaml"
      secrets_management_policy: "charter/policies/data/secrets_management_policy.yaml"

    governance:
      audit_ignore_policy: "charter/policies/governance/audit_ignore_policy.yaml"
      auditor_policy: "charter/policies/governance/auditor_policy.yaml"
      available_actions_policy: "charter/policies/governance/available_actions_policy.yaml"
      cli_governance_policy: "charter/policies/governance/cli_governance_policy.yaml"
      enforcement_model_policy: "charter/policies/governance/enforcement_model_policy.yaml"
      intent_crate_policy: "charter/policies/governance/intent_crate_policy.yaml"
      intent_guard_policy: "charter/policies/governance/intent_guard_policy.yaml"
      knowledge_source_policy: "charter/policies/governance/knowledge_source_policy.yaml"
      logging_policy: "charter/policies/governance/logging_policy.yaml"
      reporting_policy: "charter/policies/governance/reporting_policy.yaml"
      tooling_policy: "charter/policies/governance/tooling_policy.yaml"

    operations:
      canary_policy: "charter/policies/operations/canary_policy.yaml"
      dev_fastpath_policy: "charter/policies/operations/dev_fastpath_policy.yaml"
      incident_response_policy: "charter/policies/operations/incident_response_policy.yaml"

  schemas:
    policy_schema: "charter/schemas/policy_schema.json"

    agent:
      agent_policy_schema: "charter/schemas/agent/agent_policy_schema.json"
      cognitive_roles_schema: "charter/schemas/agent/cognitive_roles_schema.json"
      micro_proposal_policy_schema: "charter/schemas/agent/micro_proposal_policy_schema.json"
      resource_manifest_policy_schema: "charter/schemas/agent/resource_manifest_policy_schema.json"

    code:
      capability_tag_schema: "charter/schemas/code/capability_tag_schema.json"
      knowledge_graph_entry_schema: "charter/schemas/code/knowledge_graph_entry_schema.json"

    constitutional:
      intent_bundle_schema: "charter/schemas/constitutional/intent_bundle_schema.json"
      intent_crate_schema: "charter/schemas/constitutional/intent_crate_schema.json"
      proposal_schema: "charter/schemas/constitutional/proposal_schema.json"

    data:
      database_policy_schema: "charter/schemas/data/database_policy_schema.json"
      database_schema: "charter/schemas/data/database_schema.yaml"

    governance:
      available_actions_policy_schema: "charter/schemas/governance/available_actions_policy_schema.json"
      cli_registry_schema: "charter/schemas/governance/cli_registry_schema.json"
      enforcement_model_schema: "charter/schemas/governance/enforcement_model_schema.json"
      intent_guard_schema: "charter/schemas/governance/intent_guard_schema.json"
      reporting_policy_schema: "charter/schemas/governance/reporting_policy_schema.json"

    operations:
      canary_policy_schema: "charter/schemas/operations/canary_policy_schema.json"
      config_schema: "charter/schemas/operations/config_schema.yaml"
      runtime_requirements_schema: "charter/schemas/operations/runtime_requirements_schema.json"

mind:
  # The project_manifest is now obsolete as the database is the source of truth for capabilities.
  # project_manifest: "mind/project_manifest.yaml"

  config:
    local_mode: "mind/config/local_mode.yaml"
    runtime_requirements: "mind/config/runtime_requirements.yaml"

  evaluation:
    score_policy: "mind/evaluation/score_policy.yaml"
    audit_checklist: "mind/evaluation/audit_checklist.yaml"

  knowledge:
    entry_point_patterns: "mind/knowledge/entry_point_patterns.yaml"
    file_handlers: "mind/knowledge/file_handlers.yaml"
    source_structure: "mind/knowledge/source_structure.yaml"

  # The mind_export directory contains the canonical YAML sources for populating
  # the operational database tables.
  mind_export:
    cognitive_roles: "mind_export/cognitive_roles.yaml"
    resource_manifest: "mind_export/resource_manifest.yaml"
    capabilities: "mind_export/capabilities.yaml"
    symbols: "mind_export/symbols.yaml"
    links: "mind_export/links.yaml"
    northstar: "mind_export/northstar.yaml"

  prompts:
    capability_definer: "mind/prompts/capability_definer.prompt"
    code_peer_review: "mind/prompts/code_peer_review.prompt"
    constitutional_review: "mind/prompts/constitutional_review.prompt"
    enrich_symbol: "mind/prompts/enrich_symbol.prompt"
    fix_capability_manifest: "mind/prompts/fix_capability_manifest.prompt"
    fix_function_docstring: "mind/prompts/fix_function_docstring.prompt"
    fix_header: "mind/prompts/fix_header.prompt"
    fix_line_length: "mind/prompts/fix_line_length.prompt"
    goal_assessor: "mind/prompts/goal_assessor.prompt"
    intent_translator: "mind/prompts/intent_translator.prompt"
    module_docstring_writer: "mind/prompts/module_docstring_writer.prompt"
    new_capability_generator: "mind/prompts/new_capability_generator.prompt"
    planner_agent: "mind/prompts/planner_agent.prompt"
    refactor_for_clarity: "mind/prompts/refactor_for_clarity.prompt"
    refactor_outlier: "mind/prompts/refactor_outlier.prompt"
    standard_task_generator: "mind/prompts/standard_task_generator.prompt"
    vectorizer: "mind/prompts/vectorizer.prompt"
