# .intent/meta.yaml
version: "0.1.0"

# PURPOSE: This fulfills the evolvable_structure principle by establishing a clear
# index of all constitutional and governance files.
constitution:
  # Public keys of constitutional approvers
  approvers: "constitution/approvers.yaml"
  # Formal procedures for managing human operators
  operator_lifecycle: "constitution/operator_lifecycle.md"

mission:
  northstar: "mission/northstar.yaml"
  manifesto: "mission/manifesto.md"
  principles: "mission/principles.yaml"

policies:
  intent_guard: "policies/intent_guard.yaml"
  safety_policies: "policies/safety_policies.yaml"
  agent_reasoning_policy: "policies/agent_reasoning_policy.yaml" 
  code_health_policy: "policies/code_health_policy.yaml"
  agent_behavior_policy: "policies/agent_behavior_policy.yaml"
  tooling_policy: "policies/tooling_policy.yaml"
  enforcement_model: "policies/enforcement_model.yaml"
  secrets_management: "policies/secrets_management.yaml"
  incident_response: "policies/incident_response.yaml"
  data_privacy_policy: "policies/data_privacy.yaml"
  data_retention_policy: "policies/data_retention.yaml"
  canary_policy: "policies/canary_policy.yaml"
  agent_workflow_policy: "policies/agent_workflow_policy.yaml"
  code_style_policy: "policies/code_style_policy.yaml"
  dev_fastpath: "policies/dev_fastpath.yaml"
  audit_ignore: "policies/audit_ignore.yaml"

prompts:
  constitutional_review: "prompts/constitutional_review.prompt"
  docs_clarity_review: "prompts/docs_clarity_review.prompt"
  code_peer_review: "prompts/code_peer_review.prompt"
  module_docstring_writer: "prompts/module_docstring_writer.prompt"
  refactor_outlier: "prompts/refactor_outlier.prompt" 
  fix_header: "prompts/fix_header.prompt"

project:
  manifest_yaml: "project_manifest.yaml"

knowledge:
  source_structure: "knowledge/source_structure.yaml"
  codegraph: "knowledge/knowledge_graph.json"
  capability_tags: "knowledge/capability_tags.yaml"
  agent_roles: "knowledge/agent_roles.yaml"
  cognitive_roles: "knowledge/cognitive_roles.yaml"
  resource_manifest: "knowledge/resource_manifest.yaml"
  entry_point_patterns: "knowledge/entry_point_patterns.yaml"
  file_handlers: "knowledge/file_handlers.yaml"

evaluation:
  score_policy: "evaluation/score_policy.yaml"
  audit_checklist: "evaluation/audit_checklist.yaml"

config:
  local_mode: "config/local_mode.yaml"
  runtime_requirements: "config/runtime_requirements.yaml" 

schemas:
  config: "schemas/config_schema.yaml"
  knowledge_graph_entry: "schemas/knowledge_graph_entry.schema.json"
  proposal: "schemas/proposal.schema.json"
  agent_reasoning_policy: "schemas/agent_reasoning_policy.schema.json"
  cognitive_roles: "schemas/cognitive_roles.schema.json"
  resource_manifest: "schemas/resource_manifest.schema.json"
  canary_policy: "schemas/canary_policy.schema.json"
  data_privacy_policy: "schemas/data_privacy_policy.schema.json"
  data_retention_policy: "schemas/data_retention_policy.schema.json"
  runtime_requirements: "schemas/runtime_requirements.schema.json"
  intent_bundle: "schemas/intent_bundle.schema.json"
  enforcement_model: "schemas/enforcement_model.schema.json" # <-- ADD THIS LINE
  intent_guard: "schemas/intent_guard.schema.json" # <-- AND THIS LINE