# Generated by CORE AccumulativeTestService
# Source: src/shared/config_loader.py
# Symbols: 1

import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

from shared.config_loader import load_yaml_file


def test_load_yaml_file():
    """Test the load_yaml_file function with various scenarios."""

    # Test 1: Load valid YAML file
    with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
        yaml_content = """
        database:
          host: localhost
          port: 5432
        logging:
          level: INFO
        """
        f.write(yaml_content)
        yaml_path = Path(f.name)

    try:
        result = load_yaml_file(yaml_path)
        assert result == {
            "database": {"host": "localhost", "port": 5432},
            "logging": {"level": "INFO"},
        }
    finally:
        yaml_path.unlink()

    # Test 2: Load valid JSON file
    with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
        json_content = '{"app": {"name": "test", "version": "1.0.0"}}'
        f.write(json_content)
        json_path = Path(f.name)

    try:
        result = load_yaml_file(json_path)
        assert result == {"app": {"name": "test", "version": "1.0.0"}}
    finally:
        json_path.unlink()

    # Test 3: File not found
    non_existent_path = Path("/non/existent/file.yaml")
    with pytest.raises(FileNotFoundError) as exc_info:
        load_yaml_file(non_existent_path)
    assert str(non_existent_path) in str(exc_info.value)

    # Test 4: Unsupported file type
    with tempfile.NamedTemporaryFile(suffix=".txt", mode="w", delete=False) as f:
        f.write("some content")
        txt_path = Path(f.name)

    try:
        with pytest.raises(ValueError) as exc_info:
            load_yaml_file(txt_path)
        assert "Unsupported config file type" in str(exc_info.value)
    finally:
        txt_path.unlink()

    # Test 5: Invalid YAML content
    with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
        f.write("invalid: [yaml: content")
        invalid_yaml_path = Path(f.name)

    try:
        with pytest.raises(ValueError) as exc_info:
            load_yaml_file(invalid_yaml_path)
        assert "Invalid config format" in str(exc_info.value)
    finally:
        invalid_yaml_path.unlink()

    # Test 6: Invalid JSON content
    with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
        f.write('{"invalid": json')
        invalid_json_path = Path(f.name)

    try:
        with pytest.raises(ValueError) as exc_info:
            load_yaml_file(invalid_json_path)
        assert "Invalid config format" in str(exc_info.value)
    finally:
        invalid_json_path.unlink()

    # Test 7: Empty YAML file returns empty dict
    with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
        f.write("")
        empty_yaml_path = Path(f.name)

    try:
        result = load_yaml_file(empty_yaml_path)
        assert result == {}
    finally:
        empty_yaml_path.unlink()

    # Test 8: YAML file with only comments returns empty dict
    with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
        f.write("# This is a comment\n# Another comment\n")
        comment_yaml_path = Path(f.name)

    try:
        result = load_yaml_file(comment_yaml_path)
        assert result == {}
    finally:
        comment_yaml_path.unlink()

    # Test 9: YAML file with null content returns empty dict
    with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
        f.write("null")
        null_yaml_path = Path(f.name)

    try:
        result = load_yaml_file(null_yaml_path)
        assert result == {}
    finally:
        null_yaml_path.unlink()

    # Test 10: JSON file with null content returns empty dict
    with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
        f.write("null")
        null_json_path = Path(f.name)

    try:
        result = load_yaml_file(null_json_path)
        assert result == {}
    finally:
        null_json_path.unlink()

    # Test 11: Encoding error
    with patch("pathlib.Path.read_text") as mock_read:
        mock_read.side_effect = UnicodeDecodeError(
            "utf-8", b"", 0, 1, "invalid continuation byte"
        )

        with tempfile.NamedTemporaryFile(suffix=".yaml", mode="w", delete=False) as f:
            encoding_error_path = Path(f.name)

        try:
            with pytest.raises(ValueError) as exc_info:
                load_yaml_file(encoding_error_path)
            assert "Encoding error" in str(exc_info.value)
        finally:
            encoding_error_path.unlink()

    # Test 12: YAML file with .yml extension
    with tempfile.NamedTemporaryFile(suffix=".yml", mode="w", delete=False) as f:
        f.write("key: value")
        yml_path = Path(f.name)

    try:
        result = load_yaml_file(yml_path)
        assert result == {"key": "value"}
    finally:
        yml_path.unlink()
