# Generated by CORE AccumulativeTestService
# Source: src/shared/path_utils.py
# Symbols: 1

from pathlib import Path
from unittest.mock import Mock, patch

from shared.path_utils import copy_file


def test_copy_file():
    """Test copy_file function with various scenarios."""

    # Test 1: Basic file copy with directory creation
    src_path = Path("/source/file.txt")
    dst_path = Path("/destination/subdir/file.txt")
    test_data = b"Hello, World!"

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = test_data

        copy_file(src_path, dst_path)

        # Verify parent directory was created
        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        assert mock_mkdir.call_args[0] == ()
        assert mock_mkdir.call_args[1] == {"parents": True, "exist_ok": True}

        # Verify file was read and written
        mock_read_bytes.assert_called_once_with()
        mock_write_bytes.assert_called_once_with(test_data)

    # Test 2: File copy with existing destination directory
    src_path = Path("/source/file.txt")
    dst_path = Path("/existing/dir/file.txt")
    test_data = b"Test content"

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = test_data

        copy_file(src_path, dst_path)

        # Verify mkdir was still called (exist_ok=True handles existing dir)
        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_read_bytes.assert_called_once_with()
        mock_write_bytes.assert_called_once_with(test_data)

    # Test 3: Copy to same directory with different name
    src_path = Path("/source/original.txt")
    dst_path = Path("/source/copy.txt")
    test_data = b"Duplicate me"

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = test_data

        copy_file(src_path, dst_path)

        # Verify mkdir was called for parent directory
        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_read_bytes.assert_called_once_with()
        mock_write_bytes.assert_called_once_with(test_data)

    # Test 4: Copy with empty file
    src_path = Path("/source/empty.txt")
    dst_path = Path("/dest/empty.txt")
    empty_data = b""

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = empty_data

        copy_file(src_path, dst_path)

        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_read_bytes.assert_called_once_with()
        mock_write_bytes.assert_called_once_with(empty_data)

    # Test 5: Copy with binary data
    src_path = Path("/source/binary.bin")
    dst_path = Path("/dest/binary.bin")
    binary_data = b"\x00\x01\x02\x03\xff\xfe\xfd"

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = binary_data

        copy_file(src_path, dst_path)

        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_read_bytes.assert_called_once_with()
        mock_write_bytes.assert_called_once_with(binary_data)

    # Test 6: Verify correct paths are used
    src_path = Path("/src/file.txt")
    dst_path = Path("/dst/file.txt")
    test_data = b"Path test"

    with (
        patch.object(Path, "read_bytes") as mock_read_bytes,
        patch.object(Path, "write_bytes") as mock_write_bytes,
        patch.object(Path, "mkdir") as mock_mkdir,
    ):

        mock_read_bytes.return_value = test_data

        # Create mock objects to track which paths are used
        mock_src = Mock(spec=Path)
        mock_dst = Mock(spec=Path)
        mock_dst_parent = Mock(spec=Path)

        mock_src.read_bytes.return_value = test_data
        mock_dst.parent = mock_dst_parent
        mock_dst.write_bytes = Mock()

        copy_file(mock_src, mock_dst)

        # Verify operations on correct objects
        mock_dst_parent.mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_src.read_bytes.assert_called_once_with()
        mock_dst.write_bytes.assert_called_once_with(test_data)
