# Generated by CORE AccumulativeTestService
# Source: src/shared/time.py
# Symbols: 1

from datetime import UTC, datetime, timezone
from unittest.mock import Mock, patch

import pytest

from shared.time import now_iso


def test_now_iso():
    """Test that now_iso returns current UTC timestamp in ISO 8601 format."""
    # Test with a fixed datetime
    fixed_datetime = datetime(2023, 12, 25, 14, 30, 45, 123456, tzinfo=UTC)
    expected_iso = "2023-12-25T14:30:45.123456+00:00"

    with patch('shared.time.datetime') as mock_datetime:
        mock_datetime.now.return_value = fixed_datetime
        mock_datetime.side_effect = datetime

        result = now_iso()

        # Verify the function called datetime.now with UTC
        mock_datetime.now.assert_called_once_with(UTC)

        # Verify the result matches expected ISO format
        assert result == expected_iso

    # Test that the result is a string
    assert isinstance(result, str)

    # Test that the string can be parsed back to a datetime
    parsed_datetime = datetime.fromisoformat(result)
    assert parsed_datetime.tzinfo == timezone.utc

    # Test with different datetime to ensure it's not hardcoded
    another_fixed_datetime = datetime(2024, 1, 1, 0, 0, 0, 0, tzinfo=UTC)
    another_expected_iso = "2024-01-01T00:00:00+00:00"

    with patch('shared.time.datetime') as mock_datetime:
        mock_datetime.now.return_value = another_fixed_datetime
        mock_datetime.side_effect = datetime

        result = now_iso()

        mock_datetime.now.assert_called_once_with(UTC)
        assert result == another_expected_iso
