# Auto-generated tests for src/shared/cli_utils.py
# Generated by CORE SimpleTestGenerator
# Coverage: 5 symbols

from unittest.mock import AsyncMock, patch

# Import from source module
try:
    from shared.cli_utils import *
except ImportError:
    # Fallback if import fails
    pass


def test_async_command():
    from shared.cli_utils import async_command

    mock_async_func = AsyncMock(return_value="test_result")
    decorated_func = async_command(mock_async_func)

    result = decorated_func("arg1", kwarg1="value1")

    mock_async_func.assert_called_once_with("arg1", kwarg1="value1")
    assert result == "test_result"


def test_display_success():
    from unittest.mock import patch

    from shared.cli_utils import display_success

    with patch("shared.cli_utils.console") as mock_console:
        test_message = "Operation completed successfully"
        display_success(test_message)

        mock_console.print.assert_called_once_with(f"[green]✓[/green] {test_message}")


def test_display_error():
    from unittest.mock import patch

    from shared.cli_utils import display_error

    with patch("shared.cli_utils.console") as mock_console:
        test_message = "Test error message"
        display_error(test_message)

        mock_console.print.assert_called_once_with(
            f"[bold red]✗ {test_message}[/bold red]"
        )


def test_display_warning():
    from unittest.mock import patch

    from shared.cli_utils import display_warning

    with patch("shared.cli_utils.console") as mock_console:
        test_message = "Test warning message"
        display_warning(test_message)

        mock_console.print.assert_called_once_with(f"[yellow]⚠[/yellow] {test_message}")


def test_display_info():
    from shared.cli_utils import display_info

    with patch("shared.cli_utils.console") as mock_console:
        test_message = "Test info message"
        display_info(test_message)
        mock_console.print.assert_called_once_with(f"[blue]ℹ[/blue] {test_message}")
