# tests/body/cli/logic/test_project_docs.py
# Auto-generated tests for src/body/cli/logic/project_docs.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from __future__ import annotations

from unittest.mock import patch

import pytest

# EXPLICIT + SAFE IMPORT
try:
    from body.cli.logic.project_docs import docs

    _PROJECT_DOCS_AVAILABLE = True
except ImportError:  # pragma: no cover
    docs = None
    _PROJECT_DOCS_AVAILABLE = False


@pytest.mark.skipif(
    not _PROJECT_DOCS_AVAILABLE, reason="project_docs module not available"
)
def test_docs():
    """Test that `docs` runs the capability-doc generator and prints the path."""
    if not _PROJECT_DOCS_AVAILABLE:
        pytest.skip("project_docs module not available")

    with (
        patch("sys.argv", ["original"]),
        patch("runpy.run_module") as mock_run,
        patch("typer.echo") as mock_echo,
    ):
        docs("test_output.md")

        mock_run.assert_called_once_with(
            "features.introspection.generate_capability_docs", run_name="__main__"
        )
        mock_echo.assert_called_once_with(
            "📚 Capability documentation written to: test_output.md"  # Added emoji
        )
