# Auto-generated tests for src/mind/governance/checks/file_checks.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols


import pytest


pytestmark = pytest.mark.legacy

from unittest.mock import MagicMock, patch


# Import from source module
try:
    from mind.governance.checks.file_checks import *
except ImportError:
    # Fallback if import fails
    pass


def test_execute():
    from mind.governance.checks.file_checks import FileChecks

    with (
        patch("mind.governance.checks.file_checks.settings") as mock_settings,
        patch(
            "mind.governance.checks.file_checks.get_all_constitutional_paths"
        ) as mock_get_paths,
    ):
        mock_instance = MagicMock()
        mock_settings._meta_config = {"test": "config"}
        mock_get_paths.return_value = ["file1.md", "file2.md"]
        mock_instance._check_required_files.return_value = []
        mock_instance._check_for_orphaned_intent_files.return_value = []
        mock_instance._check_for_deprecated_files.return_value = []

        result = FileChecks.execute(mock_instance)

        assert isinstance(result, list)
