# Auto-generated tests for src/features/self_healing/policy_id_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch

# Import from source module
try:
    from features.self_healing.policy_id_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_add_missing_policy_ids():
    from features.self_healing.policy_id_service import add_missing_policy_ids

    with (
        patch("features.self_healing.policy_id_service.settings") as mock_settings,
        patch("features.self_healing.policy_id_service.console") as mock_console,
    ):
        mock_policy_file = MagicMock()
        mock_policy_file.read_text.return_value = "name: test_policy\n"
        mock_policy_file.name = "test_policy.yaml"

        mock_settings.REPO_PATH = MagicMock()
        policies_dir = mock_settings.REPO_PATH / ".intent" / "charter" / "policies"
        policies_dir.is_dir.return_value = True
        policies_dir.rglob.return_value = [mock_policy_file]

        result = add_missing_policy_ids(dry_run=True)

        assert result == 1
