# Auto-generated tests for src/features/self_healing/clarity_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch

# Import from source module
try:
    from features.self_healing.clarity_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_fix_clarity():
    from features.self_healing.clarity_service import fix_clarity

    with patch(
        "features.self_healing.clarity_service._async_fix_clarity"
    ) as mock_async:
        mock_async.return_value = None
        context = MagicMock()
        file_path = MagicMock()

        fix_clarity(context, file_path, dry_run=False)

        mock_async.assert_called_once_with(context, file_path, False)
