# Auto-generated tests for src/features/self_healing/capability_tagging_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch

# Import from source module
try:
    from features.self_healing.capability_tagging_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_tag_unassigned_capabilities():
    from pathlib import Path

    from features.self_healing.capability_tagging_service import (
        tag_unassigned_capabilities,
    )

    with patch(
        "features.self_healing.capability_tagging_service.asyncio.run"
    ) as mock_run:
        mock_cognitive_service = MagicMock()
        mock_knowledge_service = MagicMock()

        tag_unassigned_capabilities(
            mock_cognitive_service, mock_knowledge_service, Path("test_file.py"), True
        )

        mock_run.assert_called_once()
