# Auto-generated tests for src/features/self_healing/knowledge_consolidation_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch


# Import from source module
try:
    from features.self_healing.knowledge_consolidation_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_find_structurally_similar_helpers():
    from features.self_healing.knowledge_consolidation_service import (
        find_structurally_similar_helpers,
    )

    with patch(
        "features.self_healing.knowledge_consolidation_service.settings"
    ) as mock_settings:
        mock_settings.REPO_PATH = MagicMock()
        mock_settings.REPO_PATH.__truediv__.return_value.rglob.return_value = []

        result = find_structurally_similar_helpers(min_occurrences=2, max_lines=5)

        assert isinstance(result, dict)
