# Auto-generated tests for src/features/self_healing/test_failure_analyzer.py
# Generated by CORE SimpleTestGenerator
# Coverage: 3 symbols

from unittest.mock import patch

# Import from source module
try:
    from features.self_healing.test_failure_analyzer import *
except ImportError:
    # Fallback if import fails
    pass


def test_TestFailure():
    from features.self_healing.test_failure_analyzer import TestFailure

    # Create a test failure with all fields populated
    failure = TestFailure(
        test_name="test_addition",
        test_class="TestMath",
        failure_type="AssertionError",
        expected="5",
        actual="6",
        assertion="assert result == 5",
        error_message="5 != 6",
        full_context="",
    )

    # Call the method and verify the output
    result = failure.to_fix_context()

    # Check that all relevant information is included
    assert "Test: TestMath::test_addition" in result
    assert "Failure: AssertionError" in result
    assert "Expected: 5" in result
    assert "Got: 6" in result
    assert "Assertion: assert result == 5" in result
    assert "Error: 5 != 6" in result


def test_TestResults():
    from features.self_healing.test_failure_analyzer import TestResults

    # Create TestResults instance with mock data
    test_results = TestResults(
        total=10, passed=8, failed=2, failures=[], output="Test execution completed"
    )

    # Test success rate calculation
    assert test_results.success_rate == 80.0


def test_analyze():
    from features.self_healing.test_failure_analyzer import TestFailureAnalyzer

    analyzer = TestFailureAnalyzer()

    with (
        patch.object(analyzer, "_extract_summary") as mock_summary,
        patch.object(analyzer, "_extract_failures") as mock_failures,
    ):
        mock_summary.return_value = {"total": 5, "passed": 3, "failed": 2}
        mock_failures.return_value = []

        result = analyzer.analyze("test output", "test errors")

        assert result.total == 5
        assert result.passed == 3
        assert result.failed == 2
        assert result.failures == []
        assert "test output\ntest errors" in result.output
