# Auto-generated tests for src/features/self_healing/enrichment_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import AsyncMock, MagicMock, patch

# Import from source module
try:
    from features.self_healing.enrichment_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_enrich_symbols():
    from features.self_healing.enrichment_service import enrich_symbols

    with (
        patch(
            "features.self_healing.enrichment_service._get_symbols_to_enrich",
            new_callable=AsyncMock,
        ) as mock_get,
        patch(
            "features.self_healing.enrichment_service.ThrottledParallelProcessor"
        ) as mock_processor,
        patch(
            "features.self_healing.enrichment_service._update_descriptions_in_db",
            new_callable=AsyncMock,
        ) as mock_update,
    ):
        mock_get.return_value = [{"uuid": "test-uuid"}]
        mock_processor_instance = AsyncMock()
        mock_processor.return_value = mock_processor_instance
        mock_processor_instance.run_async.return_value = [
            {"uuid": "test-uuid", "description": "test description"}
        ]

        cognitive_service = MagicMock()
        qdrant_service = MagicMock()

        import asyncio

        asyncio.run(enrich_symbols(cognitive_service, qdrant_service, dry_run=False))

        mock_update.assert_called_once_with(
            [{"uuid": "test-uuid", "description": "test description"}]
        )
