# Generated by CORE AccumulativeTestService
# Source: src/test.py
# Symbols: 1

import pytest

from test import hello_world


def test_hello_world():
    """Test the hello_world function returns correct string."""
    # Test basic functionality
    result = hello_world()
    assert result == "Hello, CORE!"

    # Test return type
    assert isinstance(result, str)

    # Test string properties
    assert len(result) == 12
    assert result.startswith("Hello")
    assert result.endswith("CORE!")
    assert "CORE" in result

    # Test it's not empty
    assert result

    # Test exact match (no extra whitespace)
    assert result == "Hello, CORE!"

    # Test it doesn't contain unexpected substrings
    assert "World" not in result
    assert "hello" not in result  # case-sensitive
