# Generated by CORE AccumulativeTestService
# Source: src/main.py
# Symbols: 1

import asyncio
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from main import health_check


@pytest.mark.asyncio
async def test_health_check():
    """Test the health_check async function."""
    # Test basic functionality
    result = await health_check()

    # Check that result is a dictionary
    assert isinstance(result, dict)

    # Check that the dictionary has the expected key
    assert "status" in result

    # Check that the value is correct
    assert result["status"] == "ok"

    # Check that there are no extra keys
    assert len(result) == 1

    # Test that function returns immediately (no delay)
    start_time = datetime.now(timezone.utc)
    result = await health_check()
    end_time = datetime.now(timezone.utc)

    # Should execute very quickly (less than 0.1 seconds)
    assert (end_time - start_time).total_seconds() < 0.1

    # Test that function can be called multiple times
    results = await asyncio.gather(
        health_check(),
        health_check(),
        health_check()
    )

    # All results should be identical
    assert all(r == {"status": "ok"} for r in results)

    # Test with mocked asyncio.sleep to ensure no hidden delays
    with patch('asyncio.sleep', new_callable=AsyncMock) as mock_sleep:
        result = await health_check()
        mock_sleep.assert_not_called()
        assert result == {"status": "ok"}
