# Generated by CORE AccumulativeTestService
# Source: src/test.py
# Symbols: 1

import pytest

from test import hello_world


def test_hello_world():
    """Test the hello_world function returns correct string."""
    result = hello_world()

    assert result == "Hello, CORE!"
    assert isinstance(result, str)
    assert len(result) == 12
    assert result.startswith("Hello")
    assert result.endswith("CORE!")
    assert "CORE" in result
