# Generated by CORE AccumulativeTestService
# Source: src/api/main.py
# Symbols: 1


from fastapi import FastAPI
from fastapi.testclient import TestClient

from api.main import create_app


def test_create_app():
    """Test that create_app returns a properly configured FastAPI application."""

    # Act
    app = create_app()

    # Assert basic app configuration
    assert isinstance(app, FastAPI)
    assert app.title == "CORE - Self-Improving System Architect"
    assert app.version == "1.0.0"

    # Assert routers are included
    routes_with_prefix = [route for route in app.routes if hasattr(route, "path")]
    paths = [route.path for route in routes_with_prefix]

    # Check for health endpoint
    assert "/health" in paths

    # Check for prefixed routes (knowledge and development)
    knowledge_routes = [
        path
        for path in paths
        if path.startswith("/v1/") and "knowledge" in path.lower()
    ]
    development_routes = [
        path
        for path in paths
        if path.startswith("/v1/") and "development" in path.lower()
    ]
    assert len(knowledge_routes) > 0 or any(
        "/v1" in path for path in paths
    )  # Either specific or general check
    assert len(development_routes) > 0 or any("/v1" in path for path in paths)

    # Test health endpoint functionality
    client = TestClient(app)
    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

    # Test that exception handlers are registered by checking app state
    # (exception handlers are internal to FastAPI, but we can verify the app is functional)
    assert hasattr(app, "exception_handlers")

    # Verify lifespan is set (though we can't directly test the coroutine)
    assert hasattr(app, "router")
    assert app.router.lifespan_context is not None

    # Test that the app can handle a 404 (exception handlers working)
    response = client.get("/nonexistent")
    assert response.status_code == 404
