# Generated by CORE AccumulativeTestService
# Source: src/api/main.py
# Symbols: 1

from unittest.mock import MagicMock, Mock, patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from api.main import create_app


def test_create_app():
    """Test that create_app returns a properly configured FastAPI application."""

    # Create the app
    app = create_app()

    # Verify it's a FastAPI instance
    assert isinstance(app, FastAPI)

    # Verify basic metadata
    assert app.title == "CORE - Self-Improving System Architect"
    assert app.version == "1.0.0"

    # Verify routers are included by checking if endpoints exist
    # We'll use TestClient to verify the health endpoint
    client = TestClient(app)

    # Test health endpoint
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

    # Verify exception handlers are registered by checking if app has the expected structure
    # We can't directly test exception handlers without triggering exceptions,
    # but we can verify the app has the expected routes

    # Check that routers are mounted by looking for route prefixes
    routes = [route.path for route in app.routes]

    # Should have health endpoint
    assert "/health" in routes

    # Should have routes from included routers (checking prefixes)
    knowledge_routes = [route for route in routes if route.startswith("/v1/") and "knowledge" in route.lower()]
    development_routes = [route for route in routes if route.startswith("/v1/") and "development" in route.lower()]

    # At minimum, the prefixes should be registered
    assert any("/v1" in route for route in routes)

    # Verify lifespan is set (can't directly test without async context)
    assert hasattr(app, 'router')
    assert app.router.lifespan_context is not None

    # Test that the app can be instantiated multiple times without side effects
    app2 = create_app()
    assert isinstance(app2, FastAPI)
    assert app2.title == app.title
    assert app2.version == app.version
