---
name: Bug report
about: Create a report to help us improve
labels: [type:bug, priority:triage]
---

## Describe the bug
A clear and concise description of what the bug is.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Run '...'
3. See error '...'

## Expected behavior
What you expected to happen.

## Screenshots / Logs
If applicable, add screenshots or logs.

## Environment
- OS: [e.g. Ubuntu 22.04]
- Python: [e.g. 3.12]
- CORE commit/branch: [e.g. v0.2.0]

## Additional context
Add any other context about the problem here.
---

