---
name: Feature request
about: Suggest an idea for CORE
labels: [type:feature, size:small]
---

## Problem / Motivation
What problem are you trying to solve? Why is this important?

## Proposal
Describe the solution you'd like (high level).

## Alternatives
Describe alternatives you've considered.

## Acceptance criteria
- [ ] Criterion 1
- [ ] Criterion 2

## Additional context
Links, designs, or references.