name: Epic Proposal
description: Define a large-scale feature or refactoring effort that spans multiple issues.
labels: ["type:epic", "priority:high"]
body:
  - type: input
    id: title
    attributes:
      label: Epic Title
      description: A concise, high-level name for this body of work.
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal & Justification
      description: What is the high-level goal of this epic? Which constitutional principles does it serve?
    validations:
      required: true
  - type: textarea
    id: sub-tasks
    attributes:
      label: Sub-Tasks / Acceptance Criteria
      description: List the smaller, concrete issues that will need to be completed to close this epic.
      value: |
        - [ ] Sub-task 1
        - [ ] Sub-task 2
        - [ ] Sub-task 3