# Auto-generated tests for src/features/introspection/capability_discovery_service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 2 symbols

from unittest.mock import MagicMock


# Import from source module
try:
    from features.introspection.capability_discovery_service import *
except ImportError:
    # Fallback if import fails
    pass


def test_CapabilityRegistry():
    from features.introspection.capability_discovery_service import CapabilityRegistry

    canonical = {"read", "write"}
    aliases = {"r": "read", "w": "write"}
    registry = CapabilityRegistry(canonical, aliases)

    assert registry.resolve("read") == "read"
    assert registry.resolve("r") == "read"
    assert registry.resolve("unknown") is None


def test_validate_agent_roles():
    from features.introspection.capability_discovery_service import validate_agent_roles

    mock_registry = MagicMock()
    mock_registry.resolve.return_value = True

    agent_roles = {
        "roles": {
            "admin": {"allowed_tags": ["tag1", "tag2"]},
            "user": {"allowed_tags": ["tag3"]},
        }
    }

    validate_agent_roles(agent_roles, mock_registry)
