# Auto-generated tests for src/features/introspection/drift_detector.py
# Generated by CORE SimpleTestGenerator
# Coverage: 2 symbols

from unittest.mock import patch

# Import from source module
try:
    from features.introspection.drift_detector import *
except ImportError:
    # Fallback if import fails
    pass


def test_detect_capability_drift():
    from dataclasses import dataclass

    from features.introspection.drift_detector import detect_capability_drift

    @dataclass
    class CapabilityMeta:
        name: str
        version: str

    manifest_caps = {
        "cap1": CapabilityMeta("test", "1.0"),
        "cap2": CapabilityMeta("test2", "1.0"),
    }
    code_caps = {
        "cap1": CapabilityMeta("test", "1.0"),
        "cap3": CapabilityMeta("test3", "1.0"),
    }

    result = detect_capability_drift(manifest_caps, code_caps)

    assert result.missing_in_code == ["cap2"]
    assert result.undeclared_in_manifest == ["cap3"]
    assert result.mismatched_mappings == []


def test_write_report():
    from pathlib import Path
    from unittest.mock import Mock

    from features.introspection.drift_detector import write_report

    mock_report = Mock()
    mock_report.to_dict.return_value = {"drift_detected": False, "metrics": {}}
    test_path = Path("/test/path/report.json")

    with (
        patch.object(Path, "mkdir") as mock_mkdir,
        patch.object(Path, "write_text") as mock_write,
    ):
        write_report(test_path, mock_report)

        mock_mkdir.assert_called_once_with(parents=True, exist_ok=True)
        mock_write.assert_called_once_with(
            '{\n  "drift_detected": false,\n  "metrics": {}\n}', encoding="utf-8"
        )
