# Auto-generated tests for src/features/introspection/generate_capability_docs.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch

# Import from source module
try:
    from features.introspection.generate_capability_docs import *
except ImportError:
    # Fallback if import fails
    pass


def test_main():
    from features.introspection.generate_capability_docs import main

    with (
        patch(
            "features.introspection.generate_capability_docs._fetch_capabilities"
        ) as mock_fetch,
        patch(
            "features.introspection.generate_capability_docs.OUTPUT_PATH"
        ) as mock_output_path,
    ):
        mock_fetch.return_value = [
            {
                "capability": "test_cap",
                "domain": "test",
                "intent": "test intent",
                "file": "test.py",
                "line_number": 1,
            }
        ]
        mock_output_path.write_text = MagicMock()

        main()

        mock_fetch.assert_called_once()
        mock_output_path.write_text.assert_called_once()
