# Auto-generated tests for src/services/context/service.py
# Generated by CORE SimpleTestGenerator
# Coverage: 2 symbols

from unittest.mock import MagicMock

# Import from source module
try:
    from services.context.service import *
except ImportError:
    # Fallback if import fails
    pass


def test_ContextService():
    from services.context.service import ContextService

    # Mock dependencies
    mock_db = MagicMock()
    mock_qdrant = MagicMock()

    # Create service instance
    service = ContextService(db_service=mock_db, qdrant_client=mock_qdrant)

    # Test basic functionality
    assert service.db_provider is not None
    assert service.vector_provider is not None
    assert service.ast_provider is not None
    assert service.builder is not None
    assert service.validator is not None


def test_clear_cache():
    from services.context.service import ContextService

    # Create instance and mock the cache
    service = ContextService()
    service.cache = MagicMock()
    service.cache.clear_all.return_value = 5

    # Call the method and verify result
    result = service.clear_cache()

    # Assert the cache was cleared and correct count returned
    service.cache.clear_all.assert_called_once()
    assert result == 5
