# Auto-generated tests for src/services/context/validator.py
# Generated by CORE SimpleTestGenerator
# Coverage: 2 symbols

from unittest.mock import MagicMock, patch


# Import from source module
try:
    from services.context.validator import *
except ImportError:
    # Fallback if import fails
    pass


def test_ContextValidator():
    from services.context.validator import ContextValidator

    with patch.object(ContextValidator, "_load_schema") as mock_load:
        mock_load.return_value = {"required_fields": ["header", "context"]}
        validator = ContextValidator()

        valid_packet = {
            "header": {
                "packet_id": "test123",
                "task_id": "task456",
                "task_type": "test",
                "created_at": "2023-01-01",
                "builder_version": "1.0",
                "privacy": "local_only",
            },
            "context": [],
        }

        is_valid, errors = validator.validate(valid_packet)
        assert is_valid
        assert errors == []


def test_validate():
    from services.context.validator import ContextValidator

    validator = ContextValidator()
    validator._check_version = MagicMock(return_value=True)
    validator._validate_header = MagicMock(return_value=[])
    validator._validate_constraints = MagicMock(return_value=[])
    validator._validate_context = MagicMock(return_value=[])
    validator._validate_policy = MagicMock(return_value=[])

    packet = {"header": {"packet_id": "test123"}, "context": []}
    validator.schema = {"required_fields": ["header", "context"]}

    is_valid, errors = validator.validate(packet)

    assert is_valid is True
    assert errors == []
