# Generated by CORE AccumulativeTestService
# Source: src/shared/time.py
# Symbols: 1

from datetime import UTC, datetime
from unittest.mock import patch

from shared.time import now_iso


def test_now_iso():
    """Test that now_iso returns current UTC timestamp in ISO 8601 format."""
    # Test with a fixed datetime to ensure consistent behavior
    mock_now = datetime(2023, 12, 25, 10, 30, 45, 123456, tzinfo=UTC)
    expected_iso = "2023-12-25T10:30:45.123456+00:00"

    with patch("shared.time.datetime") as mock_datetime:
        mock_datetime.now.return_value = mock_now
        mock_datetime.side_effect = datetime

        # Call the function
        result = now_iso()

        # Verify datetime.now(UTC) was called
        mock_datetime.now.assert_called_once_with(UTC)

        # Verify the result matches expected ISO format
        assert result == expected_iso
        assert isinstance(result, str)

        # Verify the string is a valid ISO format by parsing it back
        parsed = datetime.fromisoformat(result)
        assert parsed == mock_now.replace(tzinfo=UTC)

    # Test that the function returns different values when called at different times
    with patch("shared.time.datetime") as mock_datetime:
        # First call
        mock_datetime.now.return_value = datetime(2023, 1, 1, 0, 0, 0, 0, tzinfo=UTC)
        result1 = now_iso()

        # Reset mock for second call
        mock_datetime.now.reset_mock()
        mock_datetime.now.return_value = datetime(2023, 1, 1, 0, 0, 1, 0, tzinfo=UTC)
        result2 = now_iso()

        # Results should be different
        assert result1 != result2
        assert result1 == "2023-01-01T00:00:00+00:00"
        assert result2 == "2023-01-01T00:00:01+00:00"
