# src/api/cli_user.py

"""
End-user conversational CLI interface for CORE.

This module exposes the `core` command-line binary intended for
non-technical or high-level users who wish to interact with CORE
conversationally.

Architectural Enforcement (Mind-Will-Body Separation):
-------------------------------------------------------
- User input is routed exclusively through the Will layer
  (ConversationalAgent).
- All proposals generated by the agent are validated by the Mind layer
  (constitutional governance).
- All execution is performed through Body atomic actions.

No direct execution paths bypass governance.
"""

from __future__ import annotations

import asyncio

import typer

from shared.logger import getLogger


logger = getLogger(__name__)

# Public CLI application
app = typer.Typer(name="core", help="Chat with CORE about your codebase")


@app.callback(invoke_without_command=True)
# ID: 261ee005-2111-459b-9058-2f704448cc5b
def main(
    ctx: typer.Context,
    message: str = typer.Argument(None, help="Your message to CORE"),
) -> None:
    """
    Entry point for the `core` CLI command.

    If invoked without subcommands, this function expects a single
    natural-language message which will be processed by the
    ConversationalAgent.

    Examples:
        core "analyze the CoreContext class"
        core "what does ContextBuilder do?"
        core "my tests are failing"
        core "refactor this file for clarity"

    Args:
        ctx: Typer context (used to detect subcommand invocation).
        message: Natural-language message provided by the user.

    Raises:
        typer.Exit: With status code 1 on usage error or failure.
        typer.Exit: With status code 130 on user interruption.
    """

    # If a subcommand was invoked, defer execution
    if ctx.invoked_subcommand is not None:
        return

    # Require a message when no subcommand is provided
    if not message:
        logger.info("Usage: core <message>")
        logger.info('Example: core "what does ContextBuilder do?"')
        raise typer.Exit(1)

    logger.info("User message: %s", message)

    try:
        # Execute asynchronous handler inside event loop
        asyncio.run(handle_message(message))

    except KeyboardInterrupt:
        logger.info("\n\n⚠️  Interrupted by user")
        raise typer.Exit(130)

    except Exception as exc:
        logger.error("Failed to process message: %s", exc, exc_info=True)
        logger.info("\n❌ Error: %s", exc)
        raise typer.Exit(1)


# ID: 401141cc-de0f-4c9c-ad73-a2704835f347
async def handle_message(message: str) -> None:
    """
    Asynchronous conversational handler.

    Initializes the ConversationalAgent (Will layer), processes the
    user's message, and logs the response.

    Execution Flow:
        1. Instantiate conversational agent.
        2. Delegate message processing to agent.
        3. Log formatted response.

    Args:
        message: User's natural-language query.
    """

    from will.agents.conversational import create_conversational_agent

    logger.info("🤖 CORE is thinking...\n")

    agent = await create_conversational_agent()
    response = await agent.process_message(message)

    logger.info("─" * 70)
    logger.info(response)
    logger.info("─" * 70)
    logger.info("")


if __name__ == "__main__":
    app()
