#!/usr/bin/env python3
"""scripts/production_readiness.py — production-readiness manifest → README.

The chain is: URS definition (.specs/requirements/URS-production-readiness.md)
-> attestation manifest (.specs/attestations/production-readiness.yaml)
-> generated public status (the README "Production Readiness" section).

This script is the last link. It has two modes:

  --check   (default; CI)  Validate the manifest's integrity invariants AND
                           assert the README section equals what the manifest
                           would generate. Non-zero exit on any violation/drift.
  --write                  Regenerate the README section in place, between the
                           PRODUCTION-READINESS markers.

It derives everything from the manifest — no gate list, status, or count is
hardcoded here — so it stays correct as gates close. Same discipline as
scripts/check_readme_counts.sh: the generated surface cannot silently drift
from its source of truth.

The load-bearing invariant (mirrors what G9 requires of the audit itself):
a gate may claim `met`/`mostly_met` only with dated, human-signed evidence.
An AI-produced status is never an attestation. A manifest that violates this
fails `--check`, so an over-claim cannot reach the public README.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / ".specs/attestations/production-readiness.yaml"
README = REPO_ROOT / "README.md"

START_MARK = "<!-- PRODUCTION-READINESS:START — generated by scripts/production_readiness.py; do not edit by hand -->"
END_MARK = "<!-- PRODUCTION-READINESS:END -->"

# Status vocabulary (must match the manifest's documented set), weakest first,
# with the public label + symbol rendered into the README.
STATUS_RENDER = {
    "not_started": ("⬜", "not started"),
    "not_demonstrated": ("❌", "not demonstrated"),
    "partial": ("⚠️", "partial"),
    "not_met": ("❌", "not met"),
    "mostly_met": ("🟡", "mostly met"),
    "met": ("✅", "met"),
}
# Only these two are production-passing; everything else means the gate is open.
PASSING = {"met"}
# Statuses that assert a positive verdict and therefore require attestation.
NEEDS_ATTESTATION = {"met", "mostly_met"}
# Handles that are never a valid human attester (case-insensitive, whole token).
AI_HANDLES = {"claude", "gpt", "ai", "assistant", "anthropic", "llm", "copilot", "bot", "openai"}


def load_manifest() -> dict:
    with MANIFEST.open() as fh:
        return yaml.safe_load(fh)


def validate(manifest: dict) -> list[str]:
    """Return a list of invariant violations (empty == clean)."""
    errors: list[str] = []
    gates = manifest.get("gates") or []
    if not gates:
        return ["manifest has no gates"]

    seen_ids: set[str] = set()
    for g in gates:
        gid = g.get("id", "<no-id>")
        if gid in seen_ids:
            errors.append(f"{gid}: duplicate gate id")
        seen_ids.add(gid)

        status = g.get("status")
        if status not in STATUS_RENDER:
            errors.append(f"{gid}: unknown status {status!r} (not in vocabulary)")
            continue

        att = g.get("attestation")
        # Invariant 1: met|mostly_met require evidence[] AND attestation.
        if status in NEEDS_ATTESTATION:
            if not g.get("evidence"):
                errors.append(f"{gid}: status {status} requires non-empty evidence[]")
            if not att:
                errors.append(f"{gid}: status {status} requires an attestation")
            else:
                if not att.get("verified_by"):
                    errors.append(f"{gid}: attestation missing verified_by")
                if not att.get("verified_at"):
                    errors.append(f"{gid}: attestation missing verified_at")
        # Invariant 2: attester is never an AI handle (whatever the status).
        if att and att.get("verified_by"):
            token = str(att["verified_by"]).strip().lower()
            if token in AI_HANDLES:
                errors.append(
                    f"{gid}: attestation.verified_by {att['verified_by']!r} is not a human"
                )

    # Invariant 5: overall_verdict is derived, not asserted.
    all_met = all((g.get("status") in PASSING) for g in gates)
    derived = "ATTESTED" if all_met else "NOT ATTESTED"
    stated = str(manifest.get("overall_verdict", "")).strip().upper()
    if stated != derived:
        errors.append(
            f"overall_verdict states {stated!r} but gates derive {derived!r}"
        )
    return errors


def rollup(gates: list[dict]) -> str:
    counts: dict[str, int] = {}
    for g in gates:
        counts[g["status"]] = counts.get(g["status"], 0) + 1
    total = len(gates)
    met = counts.get("met", 0)
    # Order the rollup weakest-to-strongest, omitting zero buckets (except met).
    parts = [f"**{met}/{total} met**"]
    for status in ("mostly_met", "partial", "not_met", "not_demonstrated", "not_started"):
        if counts.get(status):
            _, label = STATUS_RENDER[status]
            parts.append(f"{counts[status]} {label}")
    return " · ".join(parts)


def render_section(manifest: dict) -> str:
    gates = manifest["gates"]
    verdict = str(manifest.get("overall_verdict", "NOT ATTESTED")).strip()
    lines: list[str] = []
    lines.append("## Production Readiness")
    lines.append("")
    lines.append(
        "CORE does not claim a status it has not earned. The gates are defined in "
        "[URS-production-readiness](.specs/requirements/URS-production-readiness.md); "
        "the current verdict and per-gate evidence live in the "
        "[attestation manifest](.specs/attestations/production-readiness.yaml). "
        "This table is **generated** from that manifest — do not edit it by hand."
    )
    lines.append("")
    lines.append(f"**Production readiness: {verdict}.** All gates must hold "
                 "simultaneously, and each `met` gate must carry dated, human-signed "
                 "evidence. There is no composite score.")
    lines.append("")
    lines.append(f"Progress: {rollup(gates)}.")
    lines.append("")
    lines.append("| Gate | Status | Primary gap |")
    lines.append("|------|--------|-------------|")
    for g in gates:
        symbol, label = STATUS_RENDER[g["status"]]
        gap = (g.get("gap") or "—").replace("|", "\\|")
        lines.append(f"| {g['id']} — {g['name']} | {symbol} {label} | {gap} |")
    lines.append("")
    lines.append(
        "The full gate definitions and acceptance criteria are in "
        "[`URS-production-readiness.md`](.specs/requirements/URS-production-readiness.md); "
        "the evidence and blockers behind each status are in "
        "[`production-readiness.yaml`](.specs/attestations/production-readiness.yaml)."
    )
    return "\n".join(lines)


def splice(readme_text: str, section: str) -> str:
    """Return README text with the marked region replaced by `section`."""
    pattern = re.compile(
        re.escape(START_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    replacement = f"{START_MARK}\n{section}\n{END_MARK}"
    if not pattern.search(readme_text):
        raise SystemExit(
            "README is missing the PRODUCTION-READINESS markers; add them once "
            "around the section, then re-run --write."
        )
    return pattern.sub(lambda _m: replacement, readme_text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="regenerate the README section in place (default: check only)")
    args = ap.parse_args()

    manifest = load_manifest()
    errors = validate(manifest)
    if errors:
        print("Manifest integrity violations:")
        for e in errors:
            print(f"  FAIL  {e}")
        return 1
    print(f"Manifest integrity OK ({len(manifest['gates'])} gates, "
          f"verdict {manifest.get('overall_verdict')}).")

    section = render_section(manifest)
    readme_text = README.read_text()
    new_text = splice(readme_text, section)

    if args.write:
        if new_text != readme_text:
            README.write_text(new_text)
            print("README production-readiness section regenerated.")
        else:
            print("README already up to date.")
        return 0

    # check mode
    if new_text != readme_text:
        print("FAIL  README production-readiness section is out of sync with the "
              "manifest. Run: python scripts/production_readiness.py --write")
        return 1
    print("README production-readiness section matches the manifest.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
