# src/shared/cli/reference_markdown.py

"""Render a CLI command tree as a Markdown reference page.

Lives in shared/ so both CLIs can use it: ``core-admin`` (this repository)
and ``core`` (core-cli, which depends on core-runtime per ADR-146 D4). The
renderer takes the click command as an argument — it does NOT import any
CLI — so the page is derived from the live command tree, never from a
hand-maintained list.

Output is deterministic: commands sorted by path, hidden commands and
options omitted, no timestamps. The same tree always renders the same bytes,
so a regenerated page only changes when the CLI changed.
"""

from __future__ import annotations

import importlib
import importlib.metadata
import importlib.util
import inspect
import re
from pathlib import Path
from typing import Any

import typer


# A click command object. Typer up to 0.25 builds them from click itself;
# from 0.26 it vendors click (``typer._click``). The renderer only reads
# attributes both share, so it does not import or isinstance-check click.
Command = Any
Parameter = Any

GENERATED_MARKER = (
    "<!-- Generated by `core-admin docs generate` from the live command tree. "
    "Do not edit by hand: change the command's help text and regenerate. -->"
)


# ID: 55d93344-e290-41b5-ae6e-cee4a0862622
def click_command_for(app: typer.Typer) -> Command:
    """Return the click command tree Typer builds for ``app``."""
    return typer.main.get_command(app)


_CODE_SPAN = re.compile(r"(`+)(.+?)\1")


def _escape_prose(line: str) -> str:
    """Escape ``<`` outside code spans so ``<stem>`` is not read as an HTML tag.

    Lines indented four or more spaces render as code blocks, where an
    entity would show literally, so they are left alone.
    """
    if line.startswith("    "):
        return line
    parts: list[str] = []
    last = 0
    for match in _CODE_SPAN.finditer(line):
        parts.append(line[last : match.start()].replace("<", "&lt;"))
        parts.append(match.group(0))
        last = match.end()
    parts.append(line[last:].replace("<", "&lt;"))
    return "".join(parts)


def _help_text(text: str | None) -> str:
    """Help text as a reader sees it in ``--help``, safe to embed in Markdown.

    Drops click's ``\\f`` tail (text after it is hidden from help) and its
    ``\\b`` no-rewrap markers.
    """
    if not text:
        return ""
    text = inspect.cleandoc(text.split("\f", 1)[0])
    return "\n".join(
        _escape_prose(line) for line in text.splitlines() if line.strip() != "\b"
    )


def _is_option(param: Parameter) -> bool:
    return bool(param.param_type_name == "option")


def _is_group(command: Command) -> bool:
    return isinstance(getattr(command, "commands", None), dict)


def _first_line(text: str | None) -> str:
    help_text = _help_text(text)
    return help_text.splitlines()[0] if help_text else ""


def _cell(value: str) -> str:
    return _escape_prose(" ".join(value.split())).replace("|", "\\|")


def _default(param: Parameter) -> str:
    if param.required:
        return "required"
    default: Any = param.default
    if default is None or callable(default):
        return ""
    if _is_option(param) and param.is_flag:
        return "on" if default else "off"
    if isinstance(default, (list, tuple)):
        return ", ".join(f"`{item}`" for item in default) if default else ""
    if isinstance(default, Path):
        default = default.as_posix()
    return f"`{default}`"


def _param_name(param: Parameter) -> str:
    if _is_option(param):
        names = list(param.opts)
        if param.secondary_opts:
            names.append(" / ".join(param.secondary_opts))
        return ", ".join(f"`{name}`" for name in names)
    return f"`{(param.human_readable_name or param.name or '').upper()}`"


def _usage(path: list[str], command: Command) -> str:
    pieces = list(path)
    has_options = False
    for param in command.params:
        if getattr(param, "hidden", False):
            continue
        if param.param_type_name == "argument":
            name = (param.human_readable_name or param.name or "").upper()
            if param.nargs != 1:
                name += "..."
            pieces.append(name if param.required else f"[{name}]")
        else:
            has_options = True
    if has_options:
        pieces.append("[OPTIONS]")
    return " ".join(pieces)


def _visible_params(command: Command) -> list[Parameter]:
    return [p for p in command.params if not getattr(p, "hidden", False)]


def _render_command(path: list[str], command: Command) -> list[str]:
    anchor = "-".join(path[1:])
    lines = [f"### `{' '.join(path)}` {{#{anchor}}}", ""]
    lines += ["```", _usage(path, command), "```", ""]
    help_text = _help_text(command.help)
    if help_text:
        lines += [help_text, ""]
    params = _visible_params(command)
    if params:
        lines += ["| Argument / option | Default | Description |", "|---|---|---|"]
        for param in params:
            description = getattr(param, "help", None) or ""
            lines.append(
                f"| {_param_name(param)} | {_default(param)} | {_cell(description)} |"
            )
        lines.append("")
    return lines


def _walk(command: Command, path: list[str]) -> list[tuple[list[str], Command]]:
    if getattr(command, "hidden", False):
        return []
    if _is_group(command):
        found: list[tuple[list[str], Command]] = []
        for name in sorted(command.commands):
            found += _walk(command.commands[name], [*path, name])
        return found
    return [(path, command)]


# ID: 707e76c4-5b78-4906-9cdd-345b3df603c3
def render_cli_reference(root: Command, binary: str, intro: str = "") -> str:
    """Render ``root`` (invoked as ``binary``) as one Markdown page.

    One section per top-level group, one entry per visible command with its
    usage line, full help text and an argument/option table. ``intro`` is
    placed under the title verbatim.
    """
    commands = _walk(root, [binary])
    groups: dict[str, list[tuple[list[str], Command]]] = {}
    for path, command in commands:
        group = path[1] if len(path) > 2 else ""
        groups.setdefault(group, []).append((path, command))

    lines = [GENERATED_MARKER, "", f"# `{binary}` command reference", ""]
    if intro:
        lines += [intro.strip(), ""]
    lines += [f"{len(commands)} commands.", ""]

    group_cmds = root.commands if _is_group(root) else {}
    lines += ["| Group | Commands | Purpose |", "|---|---|---|"]
    for group, members in groups.items():
        label = group or "(top level)"
        anchor = group or "top-level"
        summary = _first_line(group_cmds[group].help) if group in group_cmds else ""
        lines.append(f"| [`{label}`](#{anchor}) | {len(members)} | {_cell(summary)} |")
    lines.append("")

    for group, members in groups.items():
        anchor = group or "top-level"
        title = f"`{binary} {group}`" if group else "Top-level commands"
        lines += ["---", "", f"## {title} {{#{anchor}}}", ""]
        group_help = _help_text(group_cmds[group].help) if group in group_cmds else ""
        if group and group_help:
            lines += [group_help, ""]
        for path, command in members:
            lines += _render_command(path, command)

    return "\n".join(lines).rstrip() + "\n"


# --- The two reference pages (ADR-167 D2) ----------------------------------
# One builder serves both `core-admin docs generate` (writes the pages) and
# the `cli.reference_current` rule (compares them), so the two can never
# disagree about what "current" means.

CORE_ADMIN_PAGE = "docs/reference/core-admin.md"
CORE_CLI_PAGE = "docs/reference/core.md"

_CORE_ADMIN_INTRO = (
    "The operator CLI, shipped in `core-runtime`. Generated from the command tree "
    "in this repository; see the [CLI overview](../cli-reference.md) for which "
    "binary does what."
)


def _core_cli_intro(version: str) -> str:
    return (
        f"The consumer CLI, shipped in `core-cli` (this page: version {version}, the "
        "released package). Most commands talk to a running CORE API. See the "
        "[CLI overview](../cli-reference.md) for which binary does what."
    )


# ID: 1f6c7272-a2ea-4cd4-98fe-48413859e203
def load_core_cli_tree() -> tuple[Command, str] | None:
    """The installed core-cli command tree and its version, or None if absent."""
    if importlib.util.find_spec("core_cli") is None:
        return None
    core_cli_main = importlib.import_module("core_cli.main")
    return click_command_for(core_cli_main.app), importlib.metadata.version("core-cli")


# ID: 9c21384a-b2d1-43dc-bc1a-277cc59f81e7
def build_reference_pages(
    core_admin_root: Command, core_cli: tuple[Command, str] | None
) -> dict[str, str]:
    """Repo-relative path -> content for each reference page that can be built.

    The ``core`` page is omitted when ``core_cli`` is None (not installed);
    callers decide whether that is a refusal or a finding.
    """
    pages = {
        CORE_ADMIN_PAGE: render_cli_reference(
            core_admin_root, "core-admin", _CORE_ADMIN_INTRO
        )
    }
    if core_cli is not None:
        root, version = core_cli
        pages[CORE_CLI_PAGE] = render_cli_reference(
            root, "core", _core_cli_intro(version)
        )
    return pages
