# src/shared/cli/reference_markdown.py

"""Render a CLI command tree as a Markdown reference page.

Lives in shared/ so both CLIs can use it: ``core-admin`` (this repository)
and ``core`` (core-cli, which depends on core-runtime per ADR-146 D4). The
renderer takes the click command as an argument — it does NOT import any
CLI — so the page is derived from the live command tree, never from a
hand-maintained list.

Output is deterministic: commands sorted by path, hidden commands and
options omitted, no timestamps. The same tree always renders the same bytes,
so a regenerated page only changes when the CLI changed.
"""

from __future__ import annotations

import inspect
import re
from pathlib import Path
from typing import Any

import click
import typer


GENERATED_MARKER = (
    "<!-- Generated by `core-admin docs generate` from the live command tree. "
    "Do not edit by hand: change the command's help text and regenerate. -->"
)


# ID: 55d93344-e290-41b5-ae6e-cee4a0862622
def click_command_for(app: typer.Typer) -> click.Command:
    """Return the click command tree Typer builds for ``app``."""
    return typer.main.get_command(app)


_CODE_SPAN = re.compile(r"(`+)(.+?)\1")


def _escape_prose(line: str) -> str:
    """Escape ``<`` outside code spans so ``<stem>`` is not read as an HTML tag.

    Lines indented four or more spaces render as code blocks, where an
    entity would show literally, so they are left alone.
    """
    if line.startswith("    "):
        return line
    parts: list[str] = []
    last = 0
    for match in _CODE_SPAN.finditer(line):
        parts.append(line[last : match.start()].replace("<", "&lt;"))
        parts.append(match.group(0))
        last = match.end()
    parts.append(line[last:].replace("<", "&lt;"))
    return "".join(parts)


def _help_text(text: str | None) -> str:
    """Help text as a reader sees it in ``--help``, safe to embed in Markdown.

    Drops click's ``\\f`` tail (text after it is hidden from help) and its
    ``\\b`` no-rewrap markers.
    """
    if not text:
        return ""
    text = inspect.cleandoc(text.split("\f", 1)[0])
    return "\n".join(
        _escape_prose(line) for line in text.splitlines() if line.strip() != "\b"
    )


def _first_line(text: str | None) -> str:
    help_text = _help_text(text)
    return help_text.splitlines()[0] if help_text else ""


def _cell(value: str) -> str:
    return _escape_prose(" ".join(value.split())).replace("|", "\\|")


def _default(param: click.Parameter) -> str:
    if param.required:
        return "required"
    default: Any = param.default
    if default is None or callable(default):
        return ""
    if isinstance(param, click.Option) and param.is_flag:
        return "on" if default else "off"
    if isinstance(default, (list, tuple)):
        return ", ".join(f"`{item}`" for item in default) if default else ""
    if isinstance(default, Path):
        default = default.as_posix()
    return f"`{default}`"


def _param_name(param: click.Parameter) -> str:
    if isinstance(param, click.Option):
        names = list(param.opts)
        if param.secondary_opts:
            names.append(" / ".join(param.secondary_opts))
        return ", ".join(f"`{name}`" for name in names)
    return f"`{(param.human_readable_name or param.name or '').upper()}`"


def _usage(path: list[str], command: click.Command) -> str:
    pieces = list(path)
    has_options = False
    for param in command.params:
        if getattr(param, "hidden", False):
            continue
        if isinstance(param, click.Argument):
            name = (param.human_readable_name or param.name or "").upper()
            if param.nargs != 1:
                name += "..."
            pieces.append(name if param.required else f"[{name}]")
        else:
            has_options = True
    if has_options:
        pieces.append("[OPTIONS]")
    return " ".join(pieces)


def _visible_params(command: click.Command) -> list[click.Parameter]:
    return [p for p in command.params if not getattr(p, "hidden", False)]


def _render_command(path: list[str], command: click.Command) -> list[str]:
    anchor = "-".join(path[1:])
    lines = [f"### `{' '.join(path)}` {{#{anchor}}}", ""]
    lines += ["```", _usage(path, command), "```", ""]
    help_text = _help_text(command.help)
    if help_text:
        lines += [help_text, ""]
    params = _visible_params(command)
    if params:
        lines += ["| Argument / option | Default | Description |", "|---|---|---|"]
        for param in params:
            description = getattr(param, "help", None) or ""
            lines.append(
                f"| {_param_name(param)} | {_default(param)} | {_cell(description)} |"
            )
        lines.append("")
    return lines


def _walk(
    command: click.Command, path: list[str]
) -> list[tuple[list[str], click.Command]]:
    if getattr(command, "hidden", False):
        return []
    if isinstance(command, click.Group):
        found: list[tuple[list[str], click.Command]] = []
        for name in sorted(command.commands):
            found += _walk(command.commands[name], [*path, name])
        return found
    return [(path, command)]


# ID: 707e76c4-5b78-4906-9cdd-345b3df603c3
def render_cli_reference(root: click.Command, binary: str, intro: str = "") -> str:
    """Render ``root`` (invoked as ``binary``) as one Markdown page.

    One section per top-level group, one entry per visible command with its
    usage line, full help text and an argument/option table. ``intro`` is
    placed under the title verbatim.
    """
    commands = _walk(root, [binary])
    groups: dict[str, list[tuple[list[str], click.Command]]] = {}
    for path, command in commands:
        group = path[1] if len(path) > 2 else ""
        groups.setdefault(group, []).append((path, command))

    lines = [GENERATED_MARKER, "", f"# `{binary}` command reference", ""]
    if intro:
        lines += [intro.strip(), ""]
    lines += [f"{len(commands)} commands.", ""]

    group_cmds = root.commands if isinstance(root, click.Group) else {}
    lines += ["| Group | Commands | Purpose |", "|---|---|---|"]
    for group, members in groups.items():
        label = group or "(top level)"
        anchor = group or "top-level"
        summary = _first_line(group_cmds[group].help) if group in group_cmds else ""
        lines.append(f"| [`{label}`](#{anchor}) | {len(members)} | {_cell(summary)} |")
    lines.append("")

    for group, members in groups.items():
        anchor = group or "top-level"
        title = f"`{binary} {group}`" if group else "Top-level commands"
        lines += ["---", "", f"## {title} {{#{anchor}}}", ""]
        group_help = _help_text(group_cmds[group].help) if group in group_cmds else ""
        if group and group_help:
            lines += [group_help, ""]
        for path, command in members:
            lines += _render_command(path, command)

    return "\n".join(lines).rstrip() + "\n"
