# .intent/charter/policies/governance/quality_assurance_policy.yaml
policy_id: 7d4f8c9a-2e1b-4f6d-9a8c-3b5e7f1d2c4a
id: quality_assurance_policy
version: "1.0.0"
title: "Quality Assurance & Test Coverage Policy"
status: active
purpose: >
  Establishes test coverage as a constitutional requirement and defines the
  autonomous self-improvement process when coverage falls below mandated thresholds.
  This policy ensures CORE maintains production-grade quality standards.

scope:
  applies_to: [code, ci, agents, governance]

owners:
  primary: "Quality Lead"
  reviewers: ["Core Maintainer", "Governance Lead"]

review:
  frequency: "6 months"

rules:
  # ===================================================================
  # RULE: Minimum Coverage Mandate
  # ===================================================================
  - id: coverage.minimum_threshold
    statement: >
      The codebase MUST maintain a minimum of 75% test coverage for all
      production code under src/. This is a constitutional requirement.
    enforcement: error
    threshold: 75
    scope: "src/"

  - id: coverage.no_untested_commits
    statement: >
      No code changes shall be committed that reduce overall test coverage
      below the constitutional minimum without explicit justification and
      a remediation plan.
    enforcement: error

  - id: coverage.new_code_requirement
    statement: >
      All new modules, classes, and public functions MUST include corresponding
      tests before integration. Coverage for new code should target 80%+.
    enforcement: warn
    threshold: 80

  # ===================================================================
  # RULE: Self-Improvement Activation
  # ===================================================================
  - id: coverage.auto_remediation
    statement: >
      When test coverage falls below the constitutional minimum, the system
      MUST automatically trigger the self-improvement service to generate
      tests and restore compliance.
    enforcement: error
    trigger: "coverage < 75%"
    action: "autonomous.quality.coverage_remediation"

  - id: coverage.remediation_priority
    statement: >
      Coverage remediation MUST prioritize modules based on: (1) criticality
      to system (core > features > utilities), (2) current coverage delta,
      (3) import/dependency count, (4) code complexity.
    enforcement: warn

  - id: coverage.remediation_validation
    statement: >
      All autonomously generated tests MUST pass the full validation pipeline
      (syntax, lint, execution) before being proposed for integration.
    enforcement: error

  # ===================================================================
  # RULE: Integration Workflow Requirements
  # ===================================================================
  - id: coverage.integration_check
    statement: >
      The integration workflow MUST include a coverage check that fails
      if coverage drops below the minimum threshold.
    enforcement: error
    integration_step: "governance.coverage_audit"

  - id: coverage.ci_enforcement
    statement: >
      CI pipelines MUST enforce coverage requirements on all PRs and
      block merges that violate the minimum threshold without approval.
    enforcement: error

  # ===================================================================
  # RULE: Reporting & Transparency
  # ===================================================================
  - id: coverage.tracking
    statement: >
      Test coverage metrics MUST be tracked in the operational ledger
      and reported in the constitutional audit.
    enforcement: warn

  - id: coverage.visibility
    statement: >
      Coverage reports MUST be generated and made visible to developers
      during integration and available via CLI commands.
    enforcement: info

# ===================================================================
# Configuration
# ===================================================================
coverage_config:
  minimum_threshold: 75
  target_threshold: 80
  critical_paths:  # These require higher coverage
    - "src/core/**/*.py: 85%"
    - "src/features/governance/**/*.py: 85%"
    - "src/features/self_healing/**/*.py: 80%"

  exclusions:  # Files excluded from coverage requirements
    - "src/**/__init__.py"
    - "src/**/models.py"  # Data models often have minimal logic
    - "tests/**/*.py"
    - "scripts/**/*.py"

  report_formats:
    - term  # Terminal output
    - html  # Detailed HTML report
    - json  # Machine-readable for auditor

  remediation_config:
    max_iterations: 10
    batch_size: 5  # Process 5 modules per iteration
    cooldown_seconds: 10
    work_directory: "work/testing"
    strategy_file: "work/testing/strategy/test_plan.md"
    goals_file: "work/testing/goals/test_goals.json"

# ===================================================================
# Autonomous Remediation Process
# ===================================================================
autonomous_remediation:
  trigger_conditions:
    - "coverage < minimum_threshold"
    - "new_uncovered_modules > 3"
    - "coverage_delta < -5%"  # Significant drop

  phases:
    - phase: strategic_analysis
      description: "Analyze codebase structure and prioritize modules for testing"
      actions:
        - "analyze_coverage_gaps"
        - "identify_critical_modules"
        - "generate_testing_strategy"

    - phase: goal_generation
      description: "Convert strategy into executable test generation goals"
      actions:
        - "parse_strategy"
        - "create_goal_queue"
        - "prioritize_by_criticality"

    - phase: test_generation
      description: "Autonomously generate and validate tests"
      actions:
        - "generate_test_code"
        - "validate_syntax_and_style"
        - "execute_tests"
        - "measure_coverage_improvement"

    - phase: integration
      description: "Propose validated tests for integration"
      actions:
        - "create_micro_proposal"
        - "submit_for_review"
        - "track_in_ledger"

# ===================================================================
# Checklist for Auditor
# ===================================================================
checklist:
  - "Verify coverage meets minimum threshold (75%)"
  - "Check that coverage check is in integration_workflow"
  - "Verify remediation service is registered as capability"
  - "Confirm CI pipeline enforces coverage gate"
  - "Audit operational ledger for coverage history"
  - "Validate exclusions are properly configured"
