
[tool.poetry]
name = "my-final-app"
version = "0.1.0"
description = "A new project governed by CORE."
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
