# ContextPackage Schema v0.2
# Constitutional definition of all LLM input context
# Last modified: 2025-11-14

version: "0.2"
schema_type: "context_package"

required_fields:
  - header
  - problem
  - scope
  - constraints
  - context
  - policy
  - provenance

structure:
  header:
    description: "Packet metadata and governance"
    required:
      - packet_id
      - task_id
      - task_type
      - created_at
      - builder_version
      - privacy
    fields:
      packet_id:
        type: string
        format: uuid
        description: "Unique identifier for this context packet"
      task_id:
        type: string
        description: "Associated task identifier"
      task_type:
        type: string
        enum: [docstring.fix, header.fix, test.generate, code.generate, refactor]
        description: "Type of task this packet serves"
      created_at:
        type: string
        format: iso8601
        description: "Packet creation timestamp"
      builder_version:
        type: string
        description: "Version of context builder"
      privacy:
        type: string
        enum: [local_only, remote_allowed]
        default: local_only
        description: "Privacy level - governs remote LLM usage"

  problem:
    description: "Task definition and acceptance criteria"
    required:
      - summary
    fields:
      summary:
        type: string
        max_length: 500
        description: "Concise problem statement"
      intent_ref:
        type: string
        description: "Reference to .intent/ policy if applicable"
      acceptance:
        type: array
        items:
          type: string
        description: "Success criteria for this task"

  scope:
    description: "Files and symbols in scope"
    required:
      - roots
    fields:
      include:
        type: array
        items:
          type: string
        description: "Paths to include (glob patterns)"
      exclude:
        type: array
        items:
          type: string
        description: "Paths to exclude (glob patterns)"
      globs:
        type: array
        items:
          type: string
        description: "Additional glob patterns"
      roots:
        type: array
        items:
          type: string
        description: "Root directories for scope"
      # --- START OF MODIFICATION ---
      traversal_depth:
        type: integer
        default: 0
        description: "Graph traversal depth. 0 = no traversal. 1 = include direct callers and callees."
      # --- END OF MODIFICATION ---

  constraints:
    description: "Resource and safety limits"
    required:
      - max_tokens
    fields:
      max_tokens:
        type: integer
        minimum: 1000
        maximum: 200000
        description: "Maximum tokens in context array"
      max_items:
        type: integer
        default: 50
        description: "Maximum number of context items"
      time_budget_seconds:
        type: integer
        description: "Maximum build time"
      cost_budget_usd:
        type: number
        description: "Maximum cost for LLM calls"
      forbidden_paths:
        type: array
        items:
          type: string
        description: "Paths that must not appear in context"
      forbidden_calls:
        type: array
        items:
          type: string
        description: "Functions/APIs that must not be referenced"

  context:
    description: "Ordered list of context items"
    type: array
    items:
      type: object
      required:
        - name
        - item_type
        - source
      fields:
        name:
          type: string
          description: "Symbol or file name"
        path:
          type: string
          description: "File path relative to project root"
        item_type:
          type: string
          enum: [symbol, snippet, summary, dependency, test, signature, code]
          description: "Type of context item"
        signature:
          type: string
          description: "Function/class signature if applicable"
        span:
          type: object
          description: "Line range in file"
          fields:
            start: {type: integer}
            end: {type: integer}
        summary:
          type: string
          max_length: 1000
          description: "Brief description of item"
        snippet:
          type: string
          max_length: 5000
          description: "Code snippet if applicable"
        deps:
          type: array
          items:
            type: string
          description: "Dependencies of this item"
        hash:
          type: string
          description: "Content hash for cache invalidation"
        source:
          type: string
          enum: [db, qdrant, ast, filesystem]
          description: "Provider that supplied this item"
        tokens_est:
          type: integer
          description: "Estimated token count"

  invariants:
    description: "Rules that must hold for valid context"
    type: array
    items:
      type: string
    examples:
      - "All symbols must have signatures"
      - "No filesystem operations in snippets"
      - "No network calls in snippets"
      - "All paths must be relative"

  policy:
    description: "Applied governance and redactions"
    required:
      - remote_allowed
    fields:
      redactions_applied:
        type: array
        items:
          type: object
          fields:
            item_name: {type: string}
            reason: {type: string}
            redacted_at: {type: string, format: iso8601}
        description: "Items removed during redaction"
      remote_allowed:
        type: boolean
        description: "Whether this packet can be sent to remote LLMs"
      notes:
        type: string
        description: "Additional policy notes"

  provenance:
    description: "Build metadata and reproducibility"
    required:
      - inputs
      - packet_hash
    fields:
      inputs:
        type: object
        description: "Input sources used"
        fields:
          db_query: {type: string}
          qdrant_query: {type: string}
          ast_files: {type: array, items: {type: string}}
      build_stats:
        type: object
        fields:
          duration_ms: {type: integer}
          items_collected: {type: integer}
          items_filtered: {type: integer}
          tokens_total: {type: integer}
      cache_key:
        type: string
        description: "Hash of task spec for cache lookup"
      packet_hash:
        type: string
        description: "Hash of entire packet for validation"

  attachments:
    description: "Optional small artifacts (templates, configs)"
    type: array
    items:
      type: object
      fields:
        name: {type: string}
        content: {type: string, max_length: 10000}
        mime_type: {type: string}

validation_rules:
  - "header.privacy must match policy.remote_allowed"
  - "sum(context[*].tokens_est) <= constraints.max_tokens"
  - "len(context) <= constraints.max_items"
  - "All context[*].path must not match constraints.forbidden_paths"
  - "provenance.packet_hash must be deterministic (same inputs → same hash)"
  - "All required_fields must be present"
