id: runtime_requirements
version: 1
title: "Runtime Requirements"
status: active
owners:
  accountable: "Platform SRE"
  responsible: ["Core Maintainer"]
review:
  frequency: "6 months"

variables:
  MIND:
    description: "The relative path to the system's declarative 'mind' (.intent directory)."
    source: env
    required: true
    type: path
    used_by: ["system", "auditor"]
  BODY:
    description: "The relative path to the system's executable 'body' (src directory)."
    source: env
    required: true
    type: path
    used_by: ["system"]
  REPO_PATH:
    description: "The absolute path to the root of the repository."
    source: env
    required: true
    type: path
    used_by: ["system","auditor"]
  LLM_ENABLED:
    description: "Master flag to enable or disable all LLM-related capabilities."
    source: env
    required: true
    type: bool
    allowed: ["true","false"]
    used_by: ["agents"]
  KEY_STORAGE_DIR:
    description: "The secure directory for storing operator private keys."
    source: env
    required: true
    type: path
    default: ".intent/keys"
    used_by: ["system"]
  CORE_ACTION_LOG_PATH:
    description: "Path to the action/change log file."
    source: env
    required: true
    type: path
    used_by: ["auditor"]
  CORE_ENV:
    description: "Runtime mode: 'development' or 'production'."
    source: env
    required: true
    type: enum
    allowed: ["development","production"]
    used_by: ["system"]
  LOG_LEVEL:
    description: "Logging level."
    source: env
    required: true
    type: enum
    allowed: ["DEBUG","INFO","WARNING","ERROR"]
    used_by: ["system"]
  CORE_DEV_FASTPATH:
    description: "Enable development fastpath."
    source: env
    required: false
    type: bool
    used_by: ["system"]
    required_when: "CORE_ENV == 'development'"

  # --- THIS IS THE NEW CONSTITUTIONAL VARIABLE ---
  CORE_MAX_CONCURRENT_REQUESTS:
    description: "The maximum number of simultaneous outbound LLM requests to prevent rate-limiting."
    source: env
    required: false
    type: integer
    default: 5
    used_by: ["system"]
  # --- END OF NEW VARIABLE ---

  DEEPSEEK_CHAT_API_URL:
    description: "API URL for the 'deepseek_chat' resource."
    source: env
    required: false
    type: uri
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  DEEPSEEK_CHAT_API_KEY:
    description: "API key for the 'deepseek_chat' resource."
    source: secret
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  DEEPSEEK_CHAT_MODEL_NAME:
    description: "Model name for the 'deepseek_chat' resource."
    source: env
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  DEEPSEEK_CODER_API_URL:
    description: "API URL for the 'deepseek_coder' resource."
    source: env
    required: false
    type: uri
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  DEEPSEEK_CODER_API_KEY:
    description: "API key for the 'deepseek_coder' resource."
    source: secret
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  DEEPSEEK_CODER_MODEL_NAME:
    description: "Model name for the 'deepseek_coder' resource."
    source: env
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  ANTHROPIC_CLAUDE_SONNET_API_URL:
    description: "API URL for the 'anthropic_claude_sonnet' resource."
    source: env
    required: false
    type: uri
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  ANTHROPIC_CLAUDE_SONNET_API_KEY:
    description: "API key for the 'anthropic_claude_sonnet' resource."
    source: secret
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"
  ANTHROPIC_CLAUDE_SONNET_MODEL_NAME:
    description: "Model name for the 'anthropic_claude_sonnet' resource."
    source: env
    required: false
    type: string
    used_by: ["agents"]
    required_when: "LLM_ENABLED == true"