# .intent/config/runtime_requirements.yaml
#
# PURPOSE: This file makes the system aware of its dependencies on the external environment.
# It allows the ConstitutionalAuditor to verify that the system is correctly configured
# at startup, without ever reading secret values.

required_environment_variables:
  - name: "MIND"
    description: "The relative path to the system's declarative 'mind' (.intent directory)."
    type: "config"
    required: true

  - name: "BODY"
    description: "The relative path to the system's executable 'body' (src directory)."
    type: "config"
    required: true

  - name: "REPO_PATH"
    description: "The absolute path to the root of the repository."
    type: "config"
    required: true

  - name: "ORCHESTRATOR_API_URL"
    description: "The API endpoint for the high-level planning LLM."
    type: "config"
    required: false
    required_when: "apis.llm.enabled == true"

  - name: "ORCHESTRATOR_API_KEY"
    description: "The API key for the high-level planning LLM."
    type: "secret"
    required: false
    required_when: "apis.llm.enabled == true"

  - name: "ORCHESTRATOR_MODEL_NAME"
    description: "The name of the model to use for orchestration."
    type: "config"
    required: false
    required_when: "apis.llm.enabled == true"

  - name: "GENERATOR_API_URL"
    description: "The API endpoint for the code generation LLM."
    type: "config"
    required: false
    required_when: "apis.llm.enabled == true"

  - name: "GENERATOR_API_KEY"
    description: "The API key for the code generation LLM."
    type: "secret"
    required: false
    required_when: "apis.llm.enabled == true"

  - name: "CORE_ACTION_LOG_PATH"
    description: "Path to .intent/change_log.json used by safety policies."
    type: "config"
    required: true

  - name: "CORE_ENV"
    description: "Runtime mode for CORE. Only 'development' or 'production' are valid."
    type: "config"
    required: true

  - name: "CORE_DEV_FASTPATH"
    description: "If 'true', relaxes procedural steps in dev (never validation). Intended for local development only."
    type: "config"
    required: false
  
  - name: "LOG_LEVEL"
    description: "Logging level: one of DEBUG, INFO, WARNING, ERROR."
    type: "config"
    required: true

  - name: "AUDITOR_MODEL"
    description: "Model name/backend used by the governance auditor."
    type: "config"
    required: false

  - name: "ALLOW_NETWORK"
    description: "Permit outbound network for agents (true/false). Default false."
    type: "config"
    required: false

  - name: "ALLOW_FS_WRITE"
    description: "Permit filesystem writes for agents (true/false). Default false."
    type: "config"
    required: false

  - name: "RISK_BUDGET"
    description: "Max cumulative risk points per release window (integer)."
    type: "config"
    required: false
