# .intent/config/runtime_requirements.yaml
#
# PURPOSE: This file makes the system aware of its dependencies on the external environment.
# It allows the ConstitutionalAuditor to verify that the system is correctly configured
# at startup, without ever reading secret values.

required_environment_variables:
  - name: "MIND"
    description: "The relative path to the system's declarative 'mind' (.intent directory)."
    type: "config"
    required: true

  - name: "BODY"
    description: "The relative path to the system's executable 'body' (src directory)."
    type: "config"
    required: true

  - name: "REPO_PATH"
    description: "The absolute path to the root of the repository."
    type: "config"
    required: true

  - name: "LLM_ENABLED"
    description: "Master flag to enable or disable all LLM-related capabilities."
    type: "config"
    required: true

  # --- LLM Resource: deepseek_chat ---
  - name: "DEEPSEEK_CHAT_API_URL"
    description: "API URL for the 'deepseek_chat' resource."
    type: "config"
    required: false
    required_when: "LLM_ENABLED == true"

  - name: "DEEPSEEK_CHAT_API_KEY"
    description: "API key for the 'deepseek_chat' resource."
    type: "secret"
    required: false
    required_when: "LLM_ENABLED == true"

  - name: "DEEPSEEK_CHAT_MODEL_NAME"
    description: "Model name for the 'deepseek_chat' resource."
    type: "config"
    required: false
    required_when: "LLM_ENABLED == true"

  # --- LLM Resource: deepseek_coder ---
  - name: "DEEPSEEK_CODER_API_URL"
    description: "API URL for the 'deepseek_coder' resource."
    type: "config"
    required: false
    required_when: "LLM_ENABLED == true"

  - name: "DEEPSEEK_CODER_API_KEY"
    description: "API key for the 'deepseek_coder' resource."
    type: "secret"
    required: false
    required_when: "LLM_ENABLED == true"

  - name: "DEEPSEEK_CODER_MODEL_NAME"
    description: "Model name for the 'deepseek_coder' resource."
    type: "config"
    required: false
    required_when: "LLM_ENABLED == true"
  
  # --- Other System Variables ---
  - name: "CORE_ACTION_LOG_PATH"
    description: "Path to the action log file."
    type: "config"
    required: true

  - name: "CORE_ENV"
    description: "Runtime mode: 'development' or 'production'."
    type: "config"
    required: true
  
  - name: "LOG_LEVEL"
    description: "Logging level: DEBUG, INFO, WARNING, ERROR."
    type: "config"
    required: true
  
  - name: "CORE_DEV_FASTPATH"
    description: "Enables development fastpath mode when set to 'true'."
    type: "config"
    required: false
    required_when: "CORE_ENV == 'development'"