# Auto-generated tests for src/features/self_healing/test_context_analyzer.py
# Generated by CORE SimpleTestGenerator
# Coverage: 1 symbols

from unittest.mock import MagicMock, patch


# Import from source module
try:
    from features.self_healing.test_context_analyzer import *
except ImportError:
    # Fallback if import fails
    pass


def test_TestContextAnalyzer():
    from features.self_healing.test_context_analyzer import TestContextAnalyzer

    with patch("features.self_healing.test_context_analyzer.settings") as mock_settings:
        mock_settings.REPO_PATH = MagicMock()
        analyzer = TestContextAnalyzer()
        assert analyzer.repo_root == mock_settings.REPO_PATH
